---
title: "Deseq"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
#library preparation
if (!requireNamespace('BiocManager', quietly = TRUE))
    install.packages('BiocManager')

  BiocManager::install('EnhancedVolcano')

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

  BiocManager::install("airway")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

  BiocManager::install("DESeq2")
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GenomicAlignments")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("edgeR")

library(EnhancedVolcano)
library(airway)
library(magrittr)
```

```{r}
#read your data
data = read.csv("D:/UNC/UNC Lab/RNA alan/R/bc/bt_glucose_gos.csv", header=TRUE)
data=data[,-1]
dat <- as.matrix(data)

head(dat)

library(GenomicAlignments)
library(DESeq2)
library(edgeR)
fls <- list.files(system.file(data, package="GenomicAlignments"))
olap <- summarizeOverlaps(dat, fls)
colnames(data)=c("Gene","log2FC")

write.csv(data,"C:/Users/datago.csv",row.names = F)
 dds <- DESeqDataSet(dat, design = ~ 1)

 
  library('DESeq2')

  dds <- DESeqDataSet(dat, design = ~ cell + dex)
  dds <- DESeq(dds, betaPrior=FALSE)
  res <- results(dds,
    contrast = c('dex','trt','untrt'))
  res <- lfcShrink(dds,
    contrast = c('dex','trt','untrt'), res=res, type = 'normal')
#plot
  dim(dat)
EnhancedVolcano(data_new,
                lab = rownames(data_new),
    x ="b" ,
    y = 'a',
    xlim = c(-10, 10),
ylim = c(0, -log10(10e-40))
)

help("EnhancedVolcano")
c = (dat[,1])
a =as.numeric(dat[,6])
b =as.numeric(dat[,3])

data_new=cbind(c,a,b)
rownames(data_new)=data_new[,1]
summary(b)
data_new=as.data.frame(data_new)
data_new$b=as.numeric(data_new$b)
data_new$a=as.numeric(data_new$a)
alpha <- 0.05 # Threshold on the adjusted p-value
cols <- densCols(dat$log2FoldChange, -log10(dat$pvalue))
plot(res$log2FoldChange, -log10(res$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")

gn.selected <- abs(res$log2FoldChange) > 2.5 & res$padj < alpha 
text(res$log2FoldChange[gn.selected],
     -log10(res$padj)[gn.selected],
     lab=rownames(res)[gn.selected ], cex=0.4)
```

